project_name: GIT_PROJECT
archives:
  - strip_parent_binary_folder: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - sample-defaults.yaml
      - src: scripts/run.sh
        dst: run.sh
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    rlcp: true
builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      # - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X=github.com/GIT_OWNER/{{ .ProjectName }}/cmd.version={{.Tag}}
    main: main.go
checksum:
  name_template: "sha256sums.txt"
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
